### ISSUE TITLE
utf-8 error while converting 

### ISSUE THREAD

**Issue by assaabriiii** [fragtastic/cis-benchmark-to-csv#23] opened 2024-07-11 13:34 UTC
Hi, im trying to convert my CIS benchmark to .csv format but when i part my pdf to the `cis2csv.py` i'll get this error : 
im using MacOS by the way i don't know its my OS problem or universal 
`python 
File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb5 in position 11: invalid start byte
`

**Comment by fragtastic** [comment] 2024-08-03 09:57
Seems to be duplicate of #14, #17, etc.
If this is not the case, feel free to reopen issue with additional context and full log output.

The converter does not accept a PDF file as input, it uses text (`.txt`) file only.

**Closed as completed by fragtastic** 2024-08-03 09:57 UTC
Labels: duplicate, invalid

**Comment by assaabriiii** [comment] 2024-08-04 05:59
yes mb i thought i should've insert pdf file so i was trying to convert it to .txt in the program, thanks.
